/*
 * Created on Sat Nov 04 2023
 *
 * This software is the proprietary property of CampusRush.
 * All rights reserved. Unauthorized copying, modification, or distribution
 * of this software, in whole or in part, is strictly prohibited.
 * For licensing information contact CampusRush.
 *
 * Copyright (c) 2023 CampusRush
 * Do not distribute
 */

const organizations = [
  "Acacia",
  "Alpha Chi Omega",
  "Alpha Chi Rho",
  "Alpha Chi Sigma",
  "Alpha Delta",
  "Alpha Delta Chi",
  "Alpha Delta Gamma",
  "Alpha Delta Phi",
  "Alpha Delta Pi",
  "Alpha Epsilon Phi",
  "Alpha Epsilon Pi",
  "Alpha Gamma Delta",
  "Alpha Gamma Omega",
  "Alpha Gamma Rho",
  "Alpha Gamma Sigma",
  "Alpha Kappa Alpha",
  "Alpha Kappa Delta Phi",
  "Alpha Kappa Lambda",
  "Alpha Kappa Phi Agonian",
  "Alpha Kappa Psi",
  "Alpha Nu Omega",
  "Alpha Omega Epsilon",
  "Alpha Omicron Pi",
  "Alpha Phi",
  "Alpha Phi Alpha",
  "Alpha Phi Delta",
  "Alpha Phi Gamma",
  "Alpha Phi Omega",
  "Alpha Pi Phi",
  "Alpha Pi Sigma",
  "Alpha Psi",
  "Alpha Psi Lambda",
  "Alpha Psi Rho",
  "Alpha Sigma Alpha",
  "Alpha Sigma Kappa",
  "Alpha Sigma Phi",
  "Alpha Sigma Rho",
  "Alpha Sigma Tau",
  "Alpha Tau Omega",
  "Alpha Theta Beta",
  "Alpha Xi Delta",
  "Beta Chi Theta",
  "Beta Gamma Nu",
  "Beta Kappa Gamma",
  "Beta Sigma Psi",
  "Beta Theta Pi",
  "Beta Upsilon Chi",
  "Chi Delta Theta",
  "Chi Omega",
  "Chi Phi",
  "Chi Psi",
  "Chi Sigma Tau",
  "Chi Sigma Xi",
  "Chi Upsilon Sigma",
  "Chi Upsilon Zeta",
  "Delphic of Gamma Sigma Tau",
  "Delta Alpha Theta",
  "Delta Chi",
  "Delta Chi Gamma",
  "Delta Chi Xi",
  "Delta Delta Delta",
  "Delta Epsilon Psi",
  "Delta Gamma",
  "Delta Kappa Delta",
  "Delta Kappa Epsilon",
  "Delta Lambda Phi",
  "Delta Omega Epsilon",
  "Delta Phi",
  "Delta Phi Epsilon",
  "Delta Phi Lambda",
  "Delta Phi Omega",
  "Delta Phi Zeta",
  "Delta Pi",
  "Delta Psi",
  "Delta Psi Delta",
  "Delta Psi Epsilon",
  "Delta Sigma",
  "Delta Sigma Chi",
  "Delta Sigma Iota",
  "Delta Sigma Phi",
  "Delta Sigma Pi",
  "Delta Sigma Theta",
  "Delta Tau Delta",
  "Delta Upsilon",
  "Delta Xi Nu",
  "Delta Xi Phi",
  "Delta Zeta",
  "Farmhouse",
  "Gamma Alpha Omega",
  "Gamma Nu Delta",
  "Gamma Phi Beta",
  "Gamma Phi Omega",
  "Gamma Sigma Sigma",
  "Gamma Zeta Alpha",
  "Iota Delta",
  "Iota Gamma Upsilon",
  "Iota Nu Delta",
  "Iota Phi Theta",
  "Kappa Alpha Order",
  "Kappa Alpha Psi",
  "Kappa Alpha Sigma",
  "Kappa Alpha Society",
  "Kappa Alpha Theta",
  "Kappa Beta Gamma",
  "Kappa Delta",
  "Kappa Delta Chi",
  "Kappa Delta Phi",
  "Kappa Delta Phi NAS",
  "Kappa Delta Rho",
  "Kappa Delta Sigma",
  "Kappa Gamma Delta",
  "Kappa Kappa Gamma",
  "Kappa Kappa Psi",
  "Kappa Phi",
  "Kappa Phi Lambda",
  "Kappa Sigma",
  "Kappa Upsilon Chi",
  "Lambda Alpha Upsilon",
  "Lambda Chi Alpha",
  "Lambda Phi Epsilon",
  "Lambda Pi Chi",
  "Lambda Pi Upsilon",
  "Lambda Psi Delta",
  "Lambda Sigma Gamma",
  "Lambda Sigma Phi",
  "Lambda Sigma Upsilon",
  "Lambda Tau Omega",
  "Lambda Theta Alpha",
  "Lambda Theta Nu",
  "Lambda Theta Phi",
  "Lambda Upsilon Lambda",
  "Mu Beta Psi",
  "Mu Sigma Upsilon",
  "Nu Alpha Kappa",
  "Omega Delta",
  "Omega Delta Phi",
  "Omega Phi Alpha",
  "Omega Phi Beta",
  "Omega Phi Chi",
  "Omega Phi Kappa",
  "Omega Psi Phi",
  "Phi Alpha Delta",
  "Phi Alpha Epsilon",
  "Phi Beta Chi",
  "Phi Beta Epsilon",
  "Phi Beta Kappa",
  "Phi Beta Sigma",
  "Phi Delta Epsilon",
  "Phi Delta Psi",
  "Phi Delta Theta",
  "Phi Gamma Delta",
  "Phi Iota Alpha",
  "Phi Kappa Pi",
  "Phi Kappa Psi",
  "Phi Kappa Sigma",
  "Phi Kappa Tau",
  "Phi Kappa Theta",
  "Phi Lambda Chi",
  "Phi Mu",
  "Phi Mu Alpha Sinfonia",
  "Phi Mu Delta",
  "Phi Rho Eta",
  "Phi Sigma Alpha",
  "Phi Sigma Kappa",
  "Phi Sigma Nu",
  "Phi Sigma Phi",
  "Phi Sigma Rho",
  "Phi Sigma Sigma",
  "Pi Alpha Phi",
  "Pi Beta Phi",
  "Pi Delta Psi",
  "Pi Kappa Alpha",
  "Pi Kappa Phi",
  "Pi Lambda Phi",
  "Pi Phi Delta",
  "Psi Sigma Phi",
  "Psi Upsilon",
  "Sigma Alpha",
  "Sigma Alpha Epsilon",
  "Sigma Alpha Epsilon Pi",
  "Sigma Alpha Mu",
  "Sigma Alpha Omega",
  "Sigma Beta Rho",
  "Sigma Chi",
  "Sigma Delta",
  "Sigma Delta AAU",
  "Sigma Delta Alpha",
  "Sigma Delta Tau",
  "Sigma Gamma Rho",
  "Sigma Iota Alpha",
  "Sigma Kappa",
  "Sigma Lambda Alpha",
  "Sigma Lambda Beta",
  "Sigma Lambda Gamma",
  "Sigma Lambda Upsilon",
  "Sigma Nu",
  "Sigma Omicron Pi",
  "Sigma Phi Beta",
  "Sigma Phi Delta",
  "Sigma Phi Epsilon",
  "Sigma Phi Lambda",
  "Sigma Phi Omega",
  "Sigma Phi Society",
  "Sigma Pi",
  "Sigma Psi Zeta",
  "Sigma Sigma Rho",
  "Sigma Sigma Sigma",
  "Sigma Tau Gamma",
  "Sigma Theta Pi",
  "Sigma Theta Psi",
  "Tau Alpha Upsilon",
  "Tau Delta Phi",
  "Tau Epsilon Phi",
  "Tau Kappa Epsilon",
  "Tau Omega Rho",
  "Tau Phi Sigma",
  "Tau Sigma Phi",
  "Theta Alpha",
  "Theta Chi",
  "Theta Delta Chi",
  "Theta Nu Xi",
  "Theta Phi Alpha",
  "Theta Phi Gamma",
  "Theta Tau",
  "Theta Xi",
  "Triangle",
  "X Club",
  "Xi Kappa",
  "Zeta Beta Tau",
  "Zeta Phi Beta",
  "Zeta Phi Gamma",
  "Zeta Phi Rho",
  "Zeta Sigma Chi",
  "Zeta Tau Alpha",
];

export default organizations;
