name: Validate Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  validate-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: |
            EAS Update
            EAS Build
