name: Label Validation
on:
  pull_request_target:
    branches: [main]
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  validate-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify PR Label
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "EAS Publish, EAS Update"
